server.port=8080

spring.application.name=apigateway
spring.main.web-application-type=servlet

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Zuul routes
zuul.routes.usermodel.path=/auth/**
zuul.routes.usermodel.url==http://localhost:8084/auth/

zuul.routes.productmodel.path=/product/**
zuul.routes.productmodel.serviceId=productmodel

zuul.routes.ordermodel.path=/order/**
zuul.routes.ordermodel.serviceId=ordermodel

zuul.routes.cartmodel.path=/cart/**
zuul.routes.cartmodel.serviceId=cartmodel


