server.port=8888
spring.application.name=configserver
spring.cloud.config.server.git.uri=git@github.com:achyutvardhan/config-repo.git
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.ignore-local-ssh-settings=true
spring.cloud.config.server.git.private-key= \
-----BEGIN OPENSSH PRIVATE KEY-----\n\
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\n\
QyNTUxOQAAACAs9gj+XvNQz7dj4v6G7jNzXtT5PQJ1Ya0h4BQpKfS2FQAAAKCUiWExlIlh\n\
MQAAAAtzc2gtZWQyNTUxOQAAACAs9gj+XvNQz7dj4v6G7jNzXtT5PQJ1Ya0h4BQpKfS2FQ\n\
AAAEAMTg+idqzu3isPY6w5A0JUpfV9hmBjN77zy8H+GI44cSz2CP5e81DPt2Pi/obuM3Ne\n\
1Pk9AnVhrSHgFCkp9LYVAAAAGmFjaHl1dHZhcmRoYW4yMzRAZ21haWwuY29tAQID\n\
-----END OPENSSH PRIVATE KEY-----\n
spring.cloud.config.server.git.clone-on-start=true


encrypt.key=mysecretkey123