server.port=8888
spring.application.name=configserver
spring.cloud.config.server.git.uri=git@github.com:achyutvardhan/config-repo.git
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.ignore-local-ssh-settings=true
spring.cloud.config.server.git.private-key=
spring.cloud.config.server.git.clone-on-start=true


encrypt.key=mysecretkey123